In [215]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [175]:
df = pd.read_csv('spam.csv', encoding='latin-1')

In [176]:
df = df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis=1)
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [177]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham              Will Ì_ b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [178]:
X = df.drop(['Category'], axis = 1)
Y = df.Category

In [184]:
X_train, X_test, Y_train, Y_test = train_test_split(df.Message, df.spam, test_size=0.2, random_state=42)

In [185]:
X_train_list = X_train.tolist()

In [224]:
v = CountVectorizer()

X_Train_cv = v.fit_transform(X_train)
X_Text_cv = v.transform(X_test)

In [225]:
X_Train_cv

<4457x7735 sparse matrix of type '<class 'numpy.int64'>'
	with 58978 stored elements in Compressed Sparse Row format>

In [226]:
X_Text_cv

<1115x7735 sparse matrix of type '<class 'numpy.int64'>'
	with 13941 stored elements in Compressed Sparse Row format>

In [227]:
X_Train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [228]:
v.get_feature_names()[5]

'0121'

In [229]:
v.vocabulary_

{'no': 4773,
 'in': 3637,
 'the': 6786,
 'same': 5872,
 'boat': 1415,
 'still': 6455,
 'here': 3416,
 'at': 1105,
 'my': 4646,
 'moms': 4549,
 'check': 1758,
 'me': 4390,
 'out': 4988,
 'on': 4912,
 'yo': 7674,
 'half': 3308,
 'naked': 4661,
 'bank': 1218,
 'of': 4869,
 'granite': 3237,
 'issues': 3749,
 'strong': 6494,
 'buy': 1580,
 'explosive': 2741,
 'pick': 5178,
 'for': 2954,
 'our': 4986,
 'members': 4423,
 'up': 7152,
 'over': 5003,
 '300': 419,
 'nasdaq': 4675,
 'symbol': 6639,
 'cdgt': 1701,
 'that': 6781,
 'is': 3739,
 '00': 0,
 'per': 5126,
 'they': 6809,
 'giving': 3157,
 'second': 5948,
 'chance': 1726,
 'to': 6906,
 'rahul': 5526,
 'dengra': 2246,
 'played': 5221,
 'smash': 6217,
 'bros': 1522,
 'lt': 4234,
 'gt': 3271,
 'religiously': 5661,
 'private': 5399,
 'your': 7685,
 '2003': 345,
 'account': 783,
 'statement': 6429,
 '07973788240': 45,
 'shows': 6108,
 '800': 630,
 'un': 7099,
 'redeemed': 5630,
 'points': 5270,
 'call': 1608,
 '08715203649': 122,
 'identifier': 

In [230]:
X_Train_cv_to_array = X_Train_cv.toarray()

In [231]:
X_Train_cv_to_array[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [232]:
model = MultinomialNB()
model.fit(X_Train_cv, Y_train)

MultinomialNB()

In [233]:
y_pred = model.predict(X_Text_cv)

In [235]:
print(classification_report(y_pred, Y_test))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       979
           1       0.89      0.99      0.94       136

    accuracy                           0.98      1115
   macro avg       0.95      0.98      0.96      1115
weighted avg       0.99      0.98      0.98      1115



In [238]:
mail = [
    '''Hey Denuwan Harshana! 

 

    Dreaming of studying at the best global universities?



    Well, here’s some exciting news! 🎉



    Yocket, India’s leading study abroad platform, is conducting exclusive events in Pune and Bangalore to help you prepare for Spring/Fall 2025 intakes.



    In this event, you will get a roadmap that your seniors implemented to get admitted into the top 100 universities.



    Here’s what you will learn:
    📌 Guidance on the Fall/Spring 2025 intake
    📌Scholarship application processes across countries
    📌Detailed process for getting Top 100 University Admits



    Mark your calendar for Pune
    📅 Date: Sat, 20 July
    🕔 Time: 5 PM to 8 PM
    🎤 Speaker: Dr. Prerna Anand, Sr. Counsellor @Yocket  
    📍 Venue: JW Marriott Hotel, Shivajinagar, Pune, Maharashtra, 411053

    Register for Pune Meetup
    Event details for Bangalore
    📅 Date: Sat, 27 July
    🕔 Time: 5 PM to 8 PM 
    🎤 Speaker: Sheebasree Vishnu, Lead Counsellor at Yocket
    📍Venue: Radisson Bengaluru City Center, Sivanchetti Gardens, Bengaluru, Karnataka 560042  ''',
    
    '''Hello ,

    The course English Learning Course with AI / Artificial Intelligence Teacher you have been following has just got updated.

    Check what's new from here View Course''',
    
    '''
    Your job alert for data science
    13 new jobs in Sri Lanka match your preferences.
    Saltside	
    Data Engineer
    Saltside · Sri Lanka (Remote)

    Bluechip Technologies Asia	
    Artificial Intelligence Researcher
    Bluechip Technologies Asia · Sri Lanka (Remote)

    Easy Apply	
    Easy Apply

    Lkcareers 	
    Data Science Manager
    Lkcareers · Colombo (On-site)

    Easy Apply	
    Easy Apply

    SYNERGEN Health	
    Associate Operation Analyst
    SYNERGEN Health · Nugegoda (On-site)

    London Metropolitan University	
    5 school alumni


    Easy Apply	
    Easy Apply

    Braintrust	
    Coders - AI Training [Remote]
    Braintrust · APJ (Remote)


    Actively recruiting

    Synergy Pharmaceuticals Corporation Private Limited	
    Analytical development Scientist
    Synergy Pharmaceuticals Corporation Private Limited · Bingiriya (On-site)

    Easy Apply	
    Easy Apply

    See all jobs''',
    
    '''
 
    
    Your job alert for information+technology
    30+ new jobs match your preferences.
    Lonza	
    Internship Global Master Data Analyst
    Lonza · Visp

    London Metropolitan University	
    11 school alumni

    Interac Corp.	
    Technical Analyst Intern
    Interac Corp. · Toronto, ON

    Zalo	
    Data QC Collaborator
    Zalo · Ho Chi Minh City, Vietnam (On-site)


    Actively recruiting


    Easy Apply	
    Easy Apply

    ektello	
    Data Analyst - Intermediate
    ektello · Universal City, CA (Hybrid)


    Actively recruiting

    SBM Offshore	
    IT Data Base Administrator Intern
    SBM Offshore · Porto (Hybrid)

    London Metropolitan University	
    1 school alum

    Accenture na Slovensku 	
    Junior IT Consultant
    Accenture na Slovensku · Bratislava (Hybrid)

    See all jobs'''
]

In [239]:
email_prediction = v.transform(mail)
model.predict(email_prediction)

array([0, 0, 1, 1], dtype=int64)